// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qujfhbauufyjdcelwyev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1amZoYmF1dWZ5amRjZWx3eWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNjc1MTYsImV4cCI6MjA2Njc0MzUxNn0.3b-xei7bs-AG1fdxqSKNZTP_1Ko8B_9ybyQDriZbl4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});